version: "3.9"

services:
  nginx:
    depends_on:
      - php
    build: ./docker/nginx/
    container_name: xount-nginx
    ports:
      - 8000:80
    volumes:
      - ${PWD}/wp:/var/www/html
      - ${PWD}/themes:/var/www/html/wp-content/themes
      - ${PWD}/plugins:/var/www/html/wp-content/plugins
      - ${PWD}/docker/php/dbadmin.php:/var/www/html/dbadmin.php
      - ${PWD}/docker/php/setup.sh:/setup.sh

  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: xount-mysql
    volumes:
      - ${HOME}/docker/xount:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: xount
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  php:
    depends_on:
      - mysql
    build: ./docker/php/
    container_name: xount-php
    volumes:
      - ${PWD}/wp:/var/www/html
      - ${PWD}/themes:/var/www/html/wp-content/themes
      - ${PWD}/plugins:/var/www/html/wp-content/plugins
      - ${PWD}/docker/php/dbadmin.php:/var/www/html/dbadmin.php
      - ${PWD}/docker/php/setup.sh:/setup.sh

    expose:
      - 9000
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: xount

volumes:
  db_data: {}
  wp: {}

